config-version: '15'

# YAML/MySQL/MariaDB
# 存储模式
data-storage-method: YAML

# MySQL settings
MySQL:
  host: localhost
  port: 3306
  user: root
  password: password
  database: minecraft
  table: nameplates_data
  properties:
    cachePrepStmts: 'true'
    prepStmtCacheSize: '250'
    prepStmtCacheSqlLimit: '2048'
    useSSL: 'false'
    verifyServerCertificate: 'false'
  Pool-Settings:
    maximum-pool-size: 10
    minimum-idle: 10
    maximum-lifetime: 180000
    idle-timeout: 60000

MariaDB:
  host: localhost
  port: 3306
  user: root
  password: password
  database: minecraft
  table: nameplates_data
  properties:
    cachePrepStmts: 'true'
    prepStmtCacheSize: '250'
    prepStmtCacheSqlLimit: '2048'
  Pool-Settings:
    maximum-pool-size: 10
    minimum-idle: 10
    maximum-lifetime: 180000
    idle-timeout: 60000