actionbar_1:
  text: '%nameplates_conditional_stamina%%nameplates_static_money_hud%%nameplates_conditional_income_actionbar%'
  conditions:
    papi-condition:
      condition_2:
        type: '=='
        papi: '%player_gamemode%'
        value: 'SURVIVAL'
actionbar_2:
  text: '%nameplates_actionbar%'