basic_info_hud:
  color: YELLOW
  overlay: PROGRESS
  dynamic-text:
    - '%nameplates_background_weather%   %nameplates_background_position%'
    - '%nameplates_background_time%   %nameplates_background_hello%'
    #- '%nameplates_conditional_region%'
  switch-interval: 15
  conditions:
    permission: bossbar.show

update_info:
  color: YELLOW
  overlay: PROGRESS
  text: '%nameplates_background_update%'
  switch-interval: 15
  conditions:
    permission: customnameplates.admin
    papi-condition:
      condition_1:
        type: '=='
        papi: '%nameplates_checkupdate%'
        value: 'true'

halloween:
  color: YELLOW
  overlay: PROGRESS
  text: '%nameplates_nameplate_halloween%'
  conditions:
    date:
      - 10/31