# Armor_Stand / Text_Display (1.19.4+)
mode: Text_Display

# Text display options
text-display-options:
  # RGBA
  background-color: 0,0,0,0
  has-shadow: false
  is-see-through: false
  use-default-background-color: false
  text-opacity: -1

# blacklist channels
# 黑名单聊天频道
blacklist-channels:
  - Private
  - Staff

# Player's default chatting bubbles
# 玩家默认聊天气泡
default-bubbles: 'chat'

# Text startFormat when no bubbles equipped
# 无气泡时的默认聊天格式
default-format:
  start: '<gradient:#F5F5F5:#E1FFFF:#F5F5F5><u>'
  end: '<!u></gradient>'

# Add additional prefix and suffix to the text
# 文字的前缀与后缀
text-prefix: ''
text-suffix: ''

# Space between two bubbles
# 两行气泡之间的间距
line-spacing: 0.4

# This decides where the bottom line is
# 第一行气泡的起始位置
bottom-line-Y-offset: 0.4

# Seconds
# This decides how long will the chat hologram remains
# 气泡的停留时间
stay-time: 8

# Plugin would send another line of bubble if the text's length exceeds a certain value
# 换行所需的字符数
characters-per-line: 30

# Plugin would ignore player's chat message when its length is over a certain value
# 单次最大文字长度
max-character-length: 100

# Cool Down
# 发送冷却
cool-down: 1